apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-fedora46-untrusted-preview
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: fedora46
    images.cnpg.io/date: "20260914"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
    images.cnpg.io/channel: preview
spec:
  images:
    - major: 19
      image: docker.io/pcm0/postgres@sha256:815e3c2686b21a3f41141b2739a85e25bce1c2629320500aac10b358cc3c7965
