apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-fedora44-untrusted
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: fedora44
    images.cnpg.io/date: "20261006"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:2197622415bc526ccd9aebbef4d7c892d7937e7b62aad1aa67a2fbd3d0e1f94e
    - major: 15
      image: docker.io/pcm0/postgres@sha256:f3415bdc0ed85286a246f7ffcb9b7ea1465cdd1c5459ae29306f116877e462f9
    - major: 16
      image: docker.io/pcm0/postgres@sha256:4aaae317b120ad40881b5643b12d7561a69c84c453089fa93687838af31138c2
    - major: 17
      image: docker.io/pcm0/postgres@sha256:eb64ecaaf2d1abd4f7ebbb5c834dfe49e62926e3a487736549c9bf30cafcb624
    - major: 18
      image: docker.io/pcm0/postgres@sha256:a1309b46898fa75f3217ed5bb6afa8299620a419a6a7b5091525753987924354
