apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-photon5-untrusted
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: photon5
    images.cnpg.io/date: "20260810"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:88e2300744fc4e0d15cd38e9df8801013d2ef121deecc072aafcbb3465d8a1b1
    - major: 15
      image: docker.io/pcm0/postgres@sha256:5f151cf626903e05e21d0b9c6ea209c7ba18d78908eb3a470c8e70b9f5d9e169
    - major: 16
      image: docker.io/pcm0/postgres@sha256:d693060aa6da7d57ed3b5078b29b439cdcbf78172ce17a8fe55602821e7e7092
    - major: 17
      image: docker.io/pcm0/postgres@sha256:afda2d5310074b3fe8442119f2b72aceafc89882676d5ceb68f9c0154e67cdb4
    - major: 18
      image: docker.io/pcm0/postgres@sha256:370b3da245dc1078b9dcefe960918e50f8498efff571aa206495c6bec9735bf5
