apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-rocky10-untrusted
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: rocky10
    images.cnpg.io/date: "20260805"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:f9808293bc7c3bd2a8ceb1a5d88292a7ea638f182c3a94d54adc05ad6080d33e
    - major: 15
      image: docker.io/pcm0/postgres@sha256:d88742ebd83077a6aa8475115c6cecb52c9d3cc4cfb7caf315fddff34ed3a204
    - major: 16
      image: docker.io/pcm0/postgres@sha256:0c0aeffe83c66622b37862e1a7101246c668d3466c48f7c6ab24cde2b92acc0b
    - major: 17
      image: docker.io/pcm0/postgres@sha256:5917cc750915e97e329951e53d42d795529bb07ef657aa722293b34ff07266d6
    - major: 18
      image: docker.io/pcm0/postgres@sha256:e1daea0bb4d33b8366db99a7d23b33c2f353d3d3e2da4808de9fb67396fc7543
