apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-fedora44-untrusted
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: fedora44
    images.cnpg.io/date: "20260805"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:5066e378e737ea941fc3d3537845e2d1c015224ae585e246869eab52080cfdf5
    - major: 15
      image: docker.io/pcm0/postgres@sha256:7da720895a9807da0f6645ffae3197fecb90acdf82be078910632110d19ad62d
    - major: 16
      image: docker.io/pcm0/postgres@sha256:cbac4da8ddaf0da8dffd0a7b2dafd108bab942335be7d8590788f68edcc1363f
    - major: 17
      image: docker.io/pcm0/postgres@sha256:1468dd168d8d3e42a65c2f3c94bbbaf3ea28b503b255b2674aa538bdc67acee3
    - major: 18
      image: docker.io/pcm0/postgres@sha256:0233f3784031b8dfca542cbae635a26bcd8bd88db9078dd7c2272668442e689c
