apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-tumbleweed-untrusted
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: tumbleweed
    images.cnpg.io/date: "20261005"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:8286f2b5d0cbc25358a953b7d3cf414251db668ef96ea638ce2cb74b974f0c1e
    - major: 15
      image: docker.io/pcm0/postgres@sha256:1ae91c371500b2ee7bf40270d9a64eaf965fd0cce59839ffce9d34fc167d9588
    - major: 16
      image: docker.io/pcm0/postgres@sha256:f2174f86b3fd5cf6f3a6dbe8efaed04a4679f36ca2e1a86ffc6109792af62e16
    - major: 17
      image: docker.io/pcm0/postgres@sha256:a76070f8563c931dc377efb475b518c0289658dfa85b8ceedea6207d9fb3b83b
    - major: 18
      image: docker.io/pcm0/postgres@sha256:e8e187d009d010d4e7b449d9f45642235fcc722c205e4805e411d273c7db4b12
