apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-azure4-untrusted-preview
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: azure4
    images.cnpg.io/date: "20260901"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
    images.cnpg.io/channel: preview
spec:
  images:
    - major: 19
      image: docker.io/pcm0/postgres@sha256:496e30036b9591661bdd6be67e4555949520123249208dc1b9cdd348bc5dcfc5
