apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-fedora44-untrusted
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: fedora44
    images.cnpg.io/date: "20260929"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:4aaa051688d1ad3856bf5fb9d9ff42a7146fe47851e794079e88c39963d6542b
    - major: 15
      image: docker.io/pcm0/postgres@sha256:87c60b2190e0edbe2a72913e16c14d78de5ffd233e529d30b56a5afea51ed544
    - major: 16
      image: docker.io/pcm0/postgres@sha256:ed32815ee6c821bc3f4a398ac4b5f0d767c25340b05d12c764fe237e6feed736
    - major: 17
      image: docker.io/pcm0/postgres@sha256:6c9851f42f9b5110b876c1adf2c85e0159a76baa8bee4a1809f5c100dcfe9a09
    - major: 18
      image: docker.io/pcm0/postgres@sha256:eba808d5a73f1ec8cda8d27ebbcbfac0044d4d04cc61124185fb0aa72c5e96b1
