apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-fedora45-untrusted
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: fedora45
    images.cnpg.io/date: "20260915"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:dc3fa26c7eacb6ac3ab441d9149dd942340474b277e3698aaf2c4733eeb10faf
    - major: 15
      image: docker.io/pcm0/postgres@sha256:1c0b1c13e0d1a57b849c6c566e8e5436322b02a35bdf339e323626abdee4d7ed
    - major: 16
      image: docker.io/pcm0/postgres@sha256:a589df32e403d30bb32df25b5d559591f50ccaf758777cdc00c4c12e3a7a05e3
    - major: 17
      image: docker.io/pcm0/postgres@sha256:15db6d914f008c53b6e82e30e305db62fea5cb6c05031709aa11017e1f0c5973
    - major: 18
      image: docker.io/pcm0/postgres@sha256:26dc93568ccfb28f1f6d2f44c76b40a024e20db81b3dff9428d229af3fdbc5ff
