apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-fedora46-untrusted-preview
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: fedora46
    images.cnpg.io/date: "20260924"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
    images.cnpg.io/channel: preview
spec:
  images:
    - major: 19
      image: docker.io/pcm0/postgres@sha256:6010747f492c8a2237158ab5142d1eb54818f191886bf3faf11545df45410454
