apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-azure4-untrusted
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: azure4
    images.cnpg.io/date: "20260929"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:be6e00ac327b7f63017ac0ecfb58d329d87dd6b8db2a53b219bf83691ce0a57e
    - major: 15
      image: docker.io/pcm0/postgres@sha256:1ec36d6c438fc5f0c95440dbff17231d38f543f61fe64e4be1fc4b1c3010e318
    - major: 16
      image: docker.io/pcm0/postgres@sha256:707cd58858165a2f954033109687095cafeec3662244bfd2c77f821f0999996d
    - major: 17
      image: docker.io/pcm0/postgres@sha256:c0886a84940325c35fa2c364b0e3f70bfc726e062e72d02e84c391c63ada812c
    - major: 18
      image: docker.io/pcm0/postgres@sha256:32aaf2bb0afd3407fcf1640d47ab77d5f529c6cca7915aa94c4162339a066819
