apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-azure4
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: azure4
    images.cnpg.io/date: "20260915"
    images.cnpg.io/publisher: docker.io
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:9b51b1a49bfe390c03242283742d4e45c4b5d3b3e0f1a8376c5f4c1afead04c6
    - major: 15
      image: docker.io/pcm0/postgres@sha256:2c0136fe3200a3345aead9bd3fb29e323c10a0e5c87af10915ef2e1952a9a41d
    - major: 16
      image: docker.io/pcm0/postgres@sha256:aa66ec330450f464ce5956a4e44d17774069f50820bfcf43fa6946c4105f2cab
    - major: 17
      image: docker.io/pcm0/postgres@sha256:2a66f47d1828b02efdd6e5ec6f7428110d3f158bbbbbbb3cb58198062e29a2b1
    - major: 18
      image: docker.io/pcm0/postgres@sha256:adeebecb9f33a1abd0301530a0453107a162c9f1afbd6dcc547277dd6dd9bb8b
