apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-azure3-untrusted
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: azure3
    images.cnpg.io/date: "20260929"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:b41e5f4e0f04a7cf3065919874b6c6599e62868f1a4d236b03aaf6cb25fd7445
    - major: 15
      image: docker.io/pcm0/postgres@sha256:cd80c6731ac8fa69bb8317f264ddf5e7c6b6f5acbcd511efefc11904ecfa5db4
    - major: 16
      image: docker.io/pcm0/postgres@sha256:6e271427a3e38c7f3a28ea552ecf952f75ab0b07070d8a6fb423b1521f44cd85
    - major: 17
      image: docker.io/pcm0/postgres@sha256:fcbcc3fa46fccfba4ff32ae0de14fd1004c74f0d461b5f213ce750c9a4b13188
    - major: 18
      image: docker.io/pcm0/postgres@sha256:9603e3886f5662a8dcbe26ace5431ad2662fb9fae68d2e5755a0c66a8effded9
