apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-fedora44
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: fedora44
    images.cnpg.io/date: "20260804"
    images.cnpg.io/publisher: docker.io
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:9e0c2ed43f32c4a3d73d69ffe95cbfc6c568c80759ceac9f4c16c60ed6dc8d7c
    - major: 15
      image: docker.io/pcm0/postgres@sha256:98783c5f5f9efa335c368b1df09d69cbd59b2edad0952d40b2d7e9cb9ac951d5
    - major: 16
      image: docker.io/pcm0/postgres@sha256:7936a464ddd081dcc5cd6072944ebb5f7a320e02ee95097570585a9f6d841101
    - major: 17
      image: docker.io/pcm0/postgres@sha256:18d78a89ebb2cd4cbdf74c372ba5bd0cb14a975a95cac1212c7051794942e867
    - major: 18
      image: docker.io/pcm0/postgres@sha256:befba92b0e99f6aa8d131417e45251e923e3eaf3a343f3a9167da920b5e667d2
