apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-rocky10-preview
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: rocky10
    images.cnpg.io/date: "20260805"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/channel: preview
spec:
  images:
    - major: 19
      image: docker.io/pcm0/postgres@sha256:887eead0007e51a2de2db092229deb1e2001b8bdc3a5ee86c061331de4d6a198
