apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-fedora46-untrusted
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: fedora46
    images.cnpg.io/date: "20261005"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:ebacd9c26d286409fb964f966ff916f8cdb1af165d8bdf9d790ef7d5dc5dc193
    - major: 15
      image: docker.io/pcm0/postgres@sha256:e4b4be4acaeed5dc26cb0587dee012b0f2e647390e66d4021160bff88331e584
    - major: 16
      image: docker.io/pcm0/postgres@sha256:2dfdc18b1f7f8335f9a2cc59471ae14b990233a898b493484b0ab7d2ddd81b81
    - major: 17
      image: docker.io/pcm0/postgres@sha256:e6463c516a056c51f79f68592bfaa98614e7db6143c456f8e9b99a86e8b8d3a2
    - major: 18
      image: docker.io/pcm0/postgres@sha256:1ae0c4adb597ffca2ca68825465da3b0c697cfba10def791ee840ed648f84a76
