apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-fedora44-untrusted-preview
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: fedora44
    images.cnpg.io/date: "20260915"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
    images.cnpg.io/channel: preview
spec:
  images:
    - major: 19
      image: docker.io/pcm0/postgres@sha256:17c65ab71e72d962d68fc7c3a6a683edd9cf19c5c1c5e92dddcdc49d1547b015
