apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-tumbleweed-untrusted
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: tumbleweed
    images.cnpg.io/date: "20260914"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:cd1ab7392009ba9b8af11fed45134f34b54306980cb998f4e7ddfdcdc32d0c21
    - major: 15
      image: docker.io/pcm0/postgres@sha256:a459d18d8148d893afaf03a4c86b0853f9e18d879a8617708d0e930a5688f4e8
    - major: 16
      image: docker.io/pcm0/postgres@sha256:85a4012dd8f035c2c3522e5699b1434440e6718003a276e6a36bf4427b8ed98c
    - major: 17
      image: docker.io/pcm0/postgres@sha256:2897e3f06a31594b3012cb5e97cc9ccde72bcf98839811f6fbfebdc2664ee5a0
    - major: 18
      image: docker.io/pcm0/postgres@sha256:a433ed49ee7e979ecdc25bc970b84d57d1b359a59ad1dfc43d940ffff64875b7
