apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-tumbleweed-untrusted
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: tumbleweed
    images.cnpg.io/date: "20260922"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:d4763e8122ba87b79d00e71160513432f1d4d8f4e19f0c40c2aed5505562cdee
    - major: 15
      image: docker.io/pcm0/postgres@sha256:97747357a4af4b0aa70900d6a1d53244295d6cd32a5c022c4a7e50ac3cba1c56
    - major: 16
      image: docker.io/pcm0/postgres@sha256:f22427025ce5a423c605327d46c78cd8405857de47702dd8fc9857db02b06f3c
    - major: 17
      image: docker.io/pcm0/postgres@sha256:d666e6e719fc52c1fc2f934baae1e9e1bc41b944310026d2276c4e5fa0a48823
    - major: 18
      image: docker.io/pcm0/postgres@sha256:185e9b3d572933ef7410cbbb39820de381198e404bbbf5ada46139da1cab1415
