apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-azure4-untrusted
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: azure4
    images.cnpg.io/date: "20260909"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:1fa150267e43d09a79fbff172adb5b7b40a99b288f263fa0d61bbb96098e939e
    - major: 15
      image: docker.io/pcm0/postgres@sha256:7c0ddacd07d7f7a9dbb6d0d25bd54d1e5829b204f4b0301fe553577baabae181
    - major: 16
      image: docker.io/pcm0/postgres@sha256:f0bb42b2180da5bd99d814ce9b8b812ee36fcaa0a6315927a86538fba08a2705
    - major: 17
      image: docker.io/pcm0/postgres@sha256:3142fdf6ee5608ebf979ded68b4eb4bc26e24dc75f37f202be29ef7784c24402
    - major: 18
      image: docker.io/pcm0/postgres@sha256:592319baacddbacb7933e5ea63231428d9383e935e7bc2c2fe489b46189c7ac0
