apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-fedora44
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: fedora44
    images.cnpg.io/date: "20260901"
    images.cnpg.io/publisher: docker.io
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:bffbe169f8787144c91cefcc1e16e5dd16265c418aed987fac680e7ed09dac63
    - major: 15
      image: docker.io/pcm0/postgres@sha256:ac07a8462fac112280cfde85b50e032fabec6a74896c75226baa7398ba7fb2c0
    - major: 16
      image: docker.io/pcm0/postgres@sha256:bcc5058b78213af557daa6c011fca304b3fe9dbda9746eab12faad8d13eabace
    - major: 17
      image: docker.io/pcm0/postgres@sha256:266f6f7a0bbe0a1bc256ac8b56974855c49ee2958403f70dc5bea5f9b5bc7042
    - major: 18
      image: docker.io/pcm0/postgres@sha256:df25aa33bb1fd4a50f088ca7be7b9de74b2e78d3fb9ffda1a04b2a4ec8015a26
