apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-alma10-untrusted
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: alma10
    images.cnpg.io/date: "20261006"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:aa5662805f161221ecec382abff5aea92a5b6632f790215dcb45b2bcadc5b77f
    - major: 15
      image: docker.io/pcm0/postgres@sha256:68716682e47a36020d2fcf8f8e746c46b667a48f6c305d60a64da56247d6a83b
    - major: 16
      image: docker.io/pcm0/postgres@sha256:124524d6eabad4888b6e2293210e10360c4ad9eaeaf2bad7bc0e67cec913b58f
    - major: 17
      image: docker.io/pcm0/postgres@sha256:8be3b0a8ec448fef97ced49f47ec5b3b9077e27ad2deeb75e1d3a485ea35b0f3
    - major: 18
      image: docker.io/pcm0/postgres@sha256:5c63b2c81ef9bcae3a386d48c04f0178be18d36e53baf61501c04de3e53a6bf9
