apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-alma10-untrusted
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: alma10
    images.cnpg.io/date: "20260907"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:80570bfe173747a3915ba3831a820a50dcd1a59892fc409870402ca51bb8739d
    - major: 15
      image: docker.io/pcm0/postgres@sha256:685f3d6ed6aee93cc11751512d933426c0b0a263d1a360dd939dff428a4d7e0e
    - major: 16
      image: docker.io/pcm0/postgres@sha256:d998841e1944baac295fba87c855f9491ddfa7ec28b0c77bfca16f279e711c78
    - major: 17
      image: docker.io/pcm0/postgres@sha256:2034bcbc65796ef1c5ff1c757717cb86edd659f9805e416afa932c0dabef5659
    - major: 18
      image: docker.io/pcm0/postgres@sha256:878babc5621dc42dc01cab529bee0e7e631c50ab938f3f2496c56a45fb9c28d3
