apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-fedora45-untrusted
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: fedora45
    images.cnpg.io/date: "20260909"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:25a890e5bd2b63a0dd6ce4bcfbcfe269135a208f9d9913113cf4de913f728338
    - major: 15
      image: docker.io/pcm0/postgres@sha256:5cefbd085f8ccae3c1f10820477c81053b46a9bca2d67c6f936fa6d601902939
    - major: 16
      image: docker.io/pcm0/postgres@sha256:3eef643035712499ed055d81d474852be9b388b73d5eae585d18f2393034a8b6
    - major: 17
      image: docker.io/pcm0/postgres@sha256:73a7ebd2a16a657a9a891ce39981dba2b7e2a718f04ad5ca2d4f66cf54ecb96f
    - major: 18
      image: docker.io/pcm0/postgres@sha256:e3a78cf1bc7681c8e9f05055b8de7600ec8938f703146dff83ac47e05faeaa31
