apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-rocky10-untrusted
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: rocky10
    images.cnpg.io/date: "20260817"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
spec:
  images:
    - major: 14
      image: docker.io/pcm0/postgres@sha256:03bd3e3ff89be9ca51a018cc3b24f38583c9575a9c7f3665aaae246d916e14c9
    - major: 15
      image: docker.io/pcm0/postgres@sha256:3296450d42330d57c83033fa2fed2db7db459ef91d301587ed8e1d851c046ece
    - major: 16
      image: docker.io/pcm0/postgres@sha256:124f6ec0e7a4a4f81d82fe0d19dbe69407c70ac8046345b0605aa11dd19fd2d2
    - major: 17
      image: docker.io/pcm0/postgres@sha256:07b2b8e47f9ab655f44d67bba7467608fdee8a712fffb6007f3237db529baab6
    - major: 18
      image: docker.io/pcm0/postgres@sha256:7f02a84e16e18a9adcf9f2a0b27fd93d13ef4dcccea5431b6f8bd3bf1b56e734
