apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-fedora45-untrusted-preview
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: fedora45
    images.cnpg.io/date: "20260922"
    images.cnpg.io/publisher: docker.io
    images.cnpg.io/languages: untrusted
    images.cnpg.io/channel: preview
spec:
  images:
    - major: 19
      image: docker.io/pcm0/postgres@sha256:192a4a43f7c8a840f3e87d972ee270e28a98e9ec1d578d5990816c07aad3b15d
